# Generated by Django 6.1.1 on 2026-09-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_tag_tasktag_task_tags_tasktag_uniq_task_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workspace.task',),
        ),
    ]
