# Generated by Django 6.1.1 on 2026-09-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_criticaltask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='timeentry',
            name='minutes_within_day',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='entry_user_date_idx',
        ),
    ]
