# Generated by Django 6.1.1 on 2026-09-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_timeentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logged_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
